In [2]:
#Data saved in csv/excel
import glob, os
import pandas as pd
import json
import warnings
warnings.filterwarnings('ignore')

data_dir="R:\MSS\Research\Projects\Baby_Toolbox\Gaze_Feasibility_2022_Data\misc"
os.chdir(data_dir)

In [3]:
#Set two decimal points for display
pd.options.display.float_format = "{:.2f}".format

In [3]:
pdc ={'2022-05-24 10.03.27': 'STL024',
 '2022-05-20 13.27.15': 'STL022',
 '2022-05-18 11.20.34': 'Sylvia B.',
 '2022-05-24 09.28.04': 'STL066',
 '2022-05-24 09.47.57': 'STL053',
 '2022-05-19 17.36.48': 'STL011',
 '2022-05-24 08.55.34': 'STL055',
 '2022-05-24 10.34.55': 'STL002',
 '2022-05-24 11.09.19': 'STL012',
 '2022-05-20 14.13.42': 'STL034',
 '2022-05-20 11.03.10': 'STL032',
 '2022-05-24 08.40.14': 'STL056',
 '2022-05-19 14.47.10': 'Porter',
 '2022-05-19 18.01.49': 'STL062',
 '2022-05-20 12.04.44': 'STL021',
 '2022-05-20 11.42.15': 'Jacob'}

In [42]:
df0.eventName.unique()

array(['beganHeadPlacement', 'completedHeadPlacement', 'beganCalibration',
       'data', 'beganCalibrationRound1', 'presentedCalibrationItem',
       'faceVerticesChanged', 'cameraImageCaptured', 'lookDetected',
       'completedCalibrationItem',
       'calibrationAlignmentCheckFailedRightEdge',
       'failedCalibrationRound', 'beganCalibrationRound2',
       'beganCalibrationRound3', 'calibrationAlignmentCheckPassed',
       'completedCalibration', 'beganLiveTest', 'presentedLiveItem',
       'beganLookDetection', 'gazeLocationChanged', 'endedLookDetection',
       'completedLiveItem', 'presentedFillerScreen',
       'removedFillerScreen', 'faceLeftScene', 'faceReturnedToScene',
       'beganHideVideo', 'beganFindVideo', 'beganRevealVideo',
       'beganDriftPresentationRound', 'presentedDriftCalibrationItem',
       'completedDriftCalibrationItem', 'completedDriftPresentationRound',
       'completedLiveTest', 'instrumentCompleted'], dtype=object)

# Read the json files and the registration files

In [4]:
jfiles = glob.glob('R:\\MSS\\Research\\Projects\\Baby_Toolbox\\Gaze_Feasibility_2022_Data\\misc\\*.json')

edoc =[]
ldoc=[]

print(len(jfiles),' files')
for file in jfiles:
    # load data using Python JSON module
    with open(file,'r') as f:
        ts = file.split('\\')[-1][:19]
        data = json.loads(f.read())
        print(ts)
        for i in range(len(data)):
            df0 = pd.json_normalize(data[i])
            subset =df0[(df0.dataKey=='userPIN')]
            sub =df0[(df0.dataKey=='assessmentName')]
            if ts in pdc:
                df0['PIN']= pdc[ts] 
            else:
                try:
                    df0['PIN'] = subset.iloc[0,5]
                except:
                    IndexError
            try:
                df0['Assessment Name'] = sub.iloc[0,5]
            except:
                IndexError
            df0['timestamp'] = ts
            #split data into LWL and EXF
            if 'LWL' in data[i][0]['itemID']:          
                ldoc.append(df0)
            else:
                edoc.append(df0)
            
           
edf = pd.concat(edoc)
ldf = pd.concat(ldoc)

92  files
2022-05-19 16.57.51
2022-05-24 10.03.27
2022-05-24 12.39.14
2022-06-06 13.34.01
2022-05-18 14.34.46
2022-05-31 15.28.52
2022-05-20 13.27.15
2022-05-23 10.13.49
2022-05-19 15.55.08
2022-06-06 13.45.53
2022-05-19 17.47.34
2022-05-20 16.01.12
2022-05-23 13.11.56
2022-05-24 14.44.25
2022-05-20 10.02.31
2022-05-23 16.39.03
2022-05-18 11.20.34
2022-05-18 09.52.01
2022-05-19 13.45.47
2022-05-19 15.08.10
2022-06-06 13.44.36
2022-05-23 18.03.03
2022-05-23 12.29.39
2022-05-19 13.37.13
2022-05-23 10.51.40
2022-05-23 16.15.25
2022-05-20 11.21.59
2022-05-25 11.24.31
2022-05-20 09.59.42
2022-05-24 09.28.04
2022-05-19 18.28.06
2022-05-24 09.47.57
2022-05-19 13.40.06
2022-05-20 16.19.02
2022-05-20 19.30.23
2022-05-19 17.36.48
2022-05-23 10.42.35
2022-05-20 16.04.49
2022-05-23 18.13.20
2022-05-18 14.21.55
2022-05-19 12.01.49
2022-05-19 11.42.45
2022-05-18 10.40.42
2022-05-20 11.06.16
2022-06-06 13.35.13
2022-05-20 14.47.37
2022-05-20 11.59.18
2022-05-20 17.36.58
2022-05-19 09.51.56
2022-05-20 16.30.17
2022-05-20 15.09.58
2022-05-24 08.55.34
2022-05-20 14.24.57
2022-05-20 16.53.05
2022-05-19 10.20.28
2022-05-23 09.57.14
2022-05-24 10.34.55
2022-05-19 11.09.42
2022-05-23 11.47.26
2022-05-25 12.44.17
2022-05-24 11.09.19
2022-05-18 14.35.30
2022-05-23 11.22.11
2022-05-21 17.30.08
2022-05-19 11.49.54
2022-05-23 09.58.04
2022-05-20 14.13.42
2022-05-21 17.07.32
2022-05-20 20.03.43
2022-05-20 13.31.55
2022-05-20 15.29.02
2022-05-20 11.03.10
2022-05-23 14.36.11
2022-05-20 10.29.37
2022-06-06 13.48.43
2022-05-20 11.37.25
2022-05-20 15.36.46
2022-05-20 11.38.10
2022-05-19 14.18.29
2022-05-23 17.50.29
2022-05-24 08.40.14
2022-05-19 12.25.36
2022-05-18 17.49.07
2022-05-20 17.35.35
2022-05-19 14.47.10
2022-05-19 18.17.21
2022-05-19 18.01.49
2022-05-20 12.04.44
2022-05-20 16.45.47
2022-05-20 12.31.30
2022-05-19 14.47.27
2022-05-20 11.42.15

In [5]:
## Filter out any ID that contains test
edf =edf[~edf['PIN'].str.contains("Practice|test|Test")]

In [6]:
ldf =ldf[~ldf['PIN'].str.contains("Practice|test|Test", na=False)]

In [7]:
edf.PIN.unique()

array(['STL051', 'STL024', 'APL046', 'MNS065', 'DAL001', 'DAL002',
       'STL022', 'APL044', 'APL032', 'MNS031', 'MNS066', 'APL003',
       'MNS011', 'DAL032', 'DAL033', 'APL051', 'APL024', 'Sylvia B.',
       'Cert 2', 'APL013', 'MNS062', 'DAL052', 'DAL025', 'STL001',
       'STL031', 'DAL023', 'APL014', 'APL064', 'DAL011', 'APL063',
       'STL066', 'STL053', 'APL012', 'APL043', 'DAL031', 'STL011',
       'APL053', 'MNS061', 'APL045', 'DAL061', 'STL063', 'MNS067',
       'MNS064', 'STL064', 'APL022', 'DAL041', 'APL011', 'DAL022',
       'STL055', 'DAL051', 'APL004', 'APL061', 'DAL042', 'STL002',
       'APL031', 'DAL024', 'DAL012', 'STL012', 'Ellie', 'APL023',
       'APL001', 'APL065', 'STL034', 'MNS041', 'DAL063', 'APL034',
       'APL042', 'STL032', 'DAL064', 'APL052', 'MNS051', 'MNS063',
       'Kinsley', 'STL041', 'APL021', 'APL041', 'APL066', 'STL056',
       'DAL021', 'MNS021', 'Porter', 'APL062', 'STL062', 'STL021',
       'STL023', 'APL033', 'APL002', 'Jacob'], dtype=object)

In [8]:
ldf.PIN.unique()

array(['STL051', 'STL024', 'APL046', 'MNS065', 'DAL001', 'DAL002',
       'STL022', 'APL044', 'APL032', 'MNS031', 'MNS066', 'APL003',
       'MNS011', 'DAL032', 'APL051', 'APL024', 'Sylvia B.', 'Cert 2',
       'APL013', 'MNS062', 'DAL052', 'DAL025', 'STL001', 'STL031',
       'DAL023', 'APL014', 'APL064', 'DAL011', 'APL063', 'STL066',
       'STL053', 'APL012', 'APL043', 'DAL031', 'STL011', 'APL053',
       'MNS061', 'APL045', nan, 'MNS067', 'MNS064', 'STL064', 'APL022',
       'DAL041', 'APL011', 'DAL022', 'STL065', 'STL055', 'APL004',
       'APL061', 'DAL042', 'STL002', 'APL031', 'DAL024', 'DAL012',
       'STL012', 'Ellie 2', 'APL023', 'APL001', 'APL065', 'STL034',
       'MNS041', 'DAL063', 'APL034', 'APL042', 'STL032', 'DAL064',
       'APL052', 'MNS051', 'MNS063', 'Kinsley', 'STL041', 'MNS022',
       'APL021', 'APL041', 'APL066', 'STL056', 'DAL021', 'MNS021',
       'Porter', 'APL062', 'STL062', 'STL021', 'STL023', 'APL033',
       'APL002', 'Jacob'], dtype=object)

In [9]:
wrong =ldf[ldf['PIN'].str.len()>6]

In [10]:
# get all reg files 
rdoc =[]
rfiles = glob.glob('R:\\MSS\\Research\\Projects\\Baby_Toolbox\\Gaze_Feasibility_2022_Data\\misc\\*Registration Data.csv')
for file in rfiles:
    if 'Narrow Structure' in file:
        pass
    else:
        data = pd.read_csv(file)
        ts = file.split('\\')[-1][:19]
        data['timestamp'] = ts
        #print(ts)
        if data.shape[0]>1:
            display(data)
        rdoc.append(data)
            

rdf = pd.concat(rdoc)

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,MNS064,E2909A06-4CF6-4F3A-A839-A30AE05F2B5B,Olivia,1:11,1.00,999.00,999.00,999.00,NaN,2,1.00,2,1,Assessment 1,2022-06-06 13.35.13
1,MNS067,E2909A06-4CF6-4F3A-A839-A30AE05F2B5B,Lets,2:0,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1,Assessment 1,2022-06-06 13.35.13
2,Practice Court,E2909A06-4CF6-4F3A-A839-A30AE05F2B5B,Mabel,1:1,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1,Assessment 1,2022-06-06 13.35.13
3,Practice Khari 2,E2909A06-4CF6-4F3A-A839-A30AE05F2B5B,Emma,0:7,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1,Assessment 1,2022-06-06 13.35.13
4,Practice test 3,E2909A06-4CF6-4F3A-A839-A30AE05F2B5B,NaN,1:11,1.00,21.00,NaN,NaN,NaN,1,1.00,1,1,Assessment 1,2022-06-06 13.35.13

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,STL031,9B9CE91A-190F-4977-97DD-BD24145A07DF,Liam,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0,1,Assessment 1,2022-05-19 16.57.51
1,STL031,9B9CE91A-190F-4977-97DD-BD24145A07DF,Liam,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0,1,NaN,2022-05-19 16.57.51
2,STL031,9B9CE91A-190F-4977-97DD-BD24145A07DF,Liam,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0,1,NaN,2022-05-19 16.57.51
3,STL051,9B9CE91A-190F-4977-97DD-BD24145A07DF,Ophelia,1:7,NaN,NaN,NaN,NaN,NaN,2,NaN,1,2,Assessment 1,2022-05-19 16.57.51
4,Test2,9B9CE91A-190F-4977-97DD-BD24145A07DF,Test,NaN,1.00,28.00,NaN,NaN,NaN,2,2.00,1,1,Assessment 1,2022-05-19 16.57.51

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,MNS031,13781795-A391-4367-BA54-1152B446E0D8,Jeremiah,1:0,1.00,999.00,999.00,999.00,NaN,1,1,2,1,Assessment 1,2022-06-06 13.45.53
1,MNS066,13781795-A391-4367-BA54-1152B446E0D8,Eliana,2:0,1.00,999.00,999.00,999.00,NaN,2,1,1,1,Assessment 1,2022-06-06 13.45.53
2,Practice louann08082920,13781795-A391-4367-BA54-1152B446E0D8,Noah,1:9,NaN,NaN,NaN,NaN,NaN,1,1,1,1,Assessment 1,2022-06-06 13.45.53
3,Practice test 2,13781795-A391-4367-BA54-1152B446E0D8,Isaiah,1:11,1.00,21.00,NaN,NaN,NaN,1,1,1,1,Assessment 1,2022-06-06 13.45.53

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,MNS051,82DD2DEB-CAF7-4996-894A-998C9EA6977A,Mace,1:5,1.00,999.00,999.00,999.00,NaN,1,1.00,1,1,Assessment 1,2022-06-06 13.48.43
1,MNS063,82DD2DEB-CAF7-4996-894A-998C9EA6977A,Joseph,1:8,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,Assessment 1,2022-06-06 13.48.43
2,Practice Test4,82DD2DEB-CAF7-4996-894A-998C9EA6977A,Isaiah,1:11,1.00,21.00,NaN,NaN,NaN,1,1.00,1,1,Assessment 1,2022-06-06 13.48.43
3,Practice-Luke,82DD2DEB-CAF7-4996-894A-998C9EA6977A,Miriam,0:3,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1,Assessment 2,2022-06-06 13.48.43

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,DAL001,10B77F95-1027-483B-9126-666988F60440,Jenean B,0:4,1,20,NaN,NaN,NaN,1,1,2,1,Assessment 1,2022-05-31 15.28.52
1,DAL002,10B77F95-1027-483B-9126-666988F60440,Jenean B,0:4,1,21,NaN,NaN,NaN,2,1,1,1,Assessment 1,2022-05-31 15.28.52

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,MIN-Test1,109DD37E-AA18-41F4-8349-41AB65A900E0,Court,48:4,27,16,NaN,NaN,NaN,1,1,1,1,Assessment 1,2022-05-18 17.49.07
1,MIN-Test2,109DD37E-AA18-41F4-8349-41AB65A900E0,MIN2,32:5,1,16,NaN,NaN,NaN,1,2,4,1,Assessment 1,2022-05-18 17.49.07
2,MIN-Test3,109DD37E-AA18-41F4-8349-41AB65A900E0,MIN3,0:11,1,24,NaN,NaN,NaN,1,2,8,1,Assessment 1,2022-05-18 17.49.07
3,Practice-test1,109DD37E-AA18-41F4-8349-41AB65A900E0,Isaiah,1:11,1,21,NaN,NaN,NaN,1,1,1,1,Assessment 1,2022-05-18 17.49.07

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,1234,BDECA77A-63E1-493E-BC64-8C3A05CD8316,Ellie Mae,2:9,2.00,21.00,NaN,NaN,NaN,2,1.00,1,1,Assessment 3,2022-05-18 14.35.30
1,Ellie,BDECA77A-63E1-493E-BC64-8C3A05CD8316,NaN,1:2,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1,Assessment 1,2022-05-18 14.35.30
2,Ellie 2,BDECA77A-63E1-493E-BC64-8C3A05CD8316,NaN,2:9,1.00,21.00,NaN,NaN,NaN,2,2.00,1,1,Assessment 1,2022-05-18 14.35.30

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,STL001,9B9CE91A-190F-4977-97DD-BD24145A07DF,Nolan,0:5,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,Assessment 1,2022-05-19 13.37.13
1,STL031,9B9CE91A-190F-4977-97DD-BD24145A07DF,Liam,0:10,NaN,NaN,NaN,NaN,NaN,1,NaN,0,1,Assessment 5,2022-05-19 13.37.13

,PIN,DeviceID,Name,Age,Education,MothersEducation,FathersEducation,GuardiansEducation,StartingLevelOverride,Gender,Handedness,Race,Ethnicity,Assessment Name,timestamp
0,Kinsley,BDECA77A-63E1-493E-BC64-8C3A05CD8316,NaN,0:5,NaN,NaN,NaN,NaN,NaN,2,NaN,1,1.00,Assessment 1,2022-05-20 11.37.25
1,Olivia,BDECA77A-63E1-493E-BC64-8C3A05CD8316,NaN,0:9,NaN,NaN,NaN,NaN,NaN,2,NaN,0,NaN,Assessment 2,2022-05-20 11.37.25
2,STL041,BDECA77A-63E1-493E-BC64-8C3A05CD8316,Tate,1:2,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1.00,Assessment 1,2022-05-20 11.37.25

In [11]:
s=rdf.groupby(['PIN','Assessment Name'])['timestamp'].count()
s[s>1]

PIN             Assessment Name
Cert 2          Assessment 1       2
Jessica         Assessment 1       3
Millennia S     Assessment 1       2
Practice Court  Assessment 1       2
Test3           Assessment 1       2
Name: timestamp, dtype: int64

# Registration cleaning

In [12]:
## Filter out any ID that contains prac or test
rdf =rdf[~rdf['PIN'].str.contains("Practice|Test")]

In [13]:
keep =['PIN','Name', 'Age', 'Assessment Name','timestamp','Age_month']

In [14]:
ldf.PIN.nunique()

86

In [15]:
rdf['Age'] = rdf['Age'].fillna(rdf.groupby('PIN')['Age'].transform('first'))

In [16]:
rdf[['Year','Month']] = rdf.Age.str.split(":",expand=True)

In [17]:
rdf['Month'] =pd.to_numeric(rdf['Month'])
rdf['Year'] =pd.to_numeric(rdf['Year'])

In [18]:
#recode the age into months format
rdf['Age_month'] = rdf['Year']*12 + rdf['Month']

In [19]:
rsub =rdf[keep].drop_duplicates()

In [20]:
edf.shape

(2551999, 16)

## how many rounds of calibration does a person take (options are 1, 2, or 3 per record)

## how many times is the "eventName" : "failedCalibrationRound" on round 3

In [5]:
def onetwothree(df):
    #The timestamp with 3 calibration
    d3 =df[(df.gazeEngineState=='calibrating') & (df.itemID.str.contains('Calibration3'))][['PIN','Assessment Name','timestamp']].drop_duplicates()
    #The timestamp with 2 calibration
    d2 =df[(df.gazeEngineState=='calibrating')& (df.itemID.str.contains('Calibration2'))][['PIN','Assessment Name','timestamp']].drop_duplicates()
    d1 =df[(df.gazeEngineState=='calibrating') & (df.itemID.str.contains('Calibration1'))][['PIN','Assessment Name','timestamp']].drop_duplicates()
    print(d3.shape[0], 'people had 3 rounds of calibrations.' )
    print(d2.shape[0]-d3.shape[0], 'people had 2 rounds of calibrations.' )
    print(d1.shape[0]-d2.shape[0], 'people had 1 round of calibration.' )
    #13 times is the "eventName" : "failedCalibrationRound" on round 3
    third = df[(df.itemID.str.contains('Calibration3'))&(df.eventName.str.contains('failedCalibrationRound'))][['PIN','Assessment Name','timestamp']].drop_duplicates()
    print('')
    print(third.shape[0] ,'times is the "eventName" : "failedCalibrationRound" on round 3')
    display(third.head())

    two= pd.merge(d2,d3, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)   
    one= pd.merge(d1,d2, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
    
    return d3,two, one, third

In [6]:
#EXF
e3, e2,e1,ef =onetwothree(edf)

40 people had 3 rounds of calibrations.
19 people had 2 rounds of calibrations.
29 people had 1 round of calibration.

33 times is the "eventName" : "failedCalibrationRound" on round 3

           PIN Assessment Name            timestamp
34591   STL024    Assessment 1  2022-05-24 10.03.27
62170   APL046    Assessment 1  2022-05-24 12.39.14
71926   MNS065    Assessment 1  2022-06-06 13.34.01
159632  STL022    Assessment 2  2022-05-20 13.27.15
198425  APL032    Assessment 1  2022-05-19 15.55.08

In [8]:
#LWL F2
l3, l2, l1 ,lf=onetwothree(ldf)

37 people had 3 rounds of calibrations.
18 people had 2 rounds of calibrations.
31 people had 1 round of calibration.

30 times is the "eventName" : "failedCalibrationRound" on round 3

           PIN Assessment Name            timestamp
21032   STL024    Assessment 1  2022-05-24 10.03.27
57366   MNS065    Assessment 1  2022-06-06 13.34.01
78181   DAL001    Assessment 1  2022-05-31 15.28.52
155361  APL032    Assessment 1  2022-05-19 15.55.08
190425  MNS066    Assessment 1  2022-06-06 13.45.53

In [23]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('C:\\Users\\tsb7592\\OneDrive - Northwestern University\\Gaze_Feasibility_2022\\calibrating.xlsx', engine='xlsxwriter')

#b. Summarize (inc. medians) by measure, overall and by age group
e1.to_excel(writer, sheet_name='EXF_F1_1',index=False)
e2.to_excel(writer, sheet_name='EXF_F1_2',index=False)
e3.to_excel(writer, sheet_name='EXF_F1_3',index=False)
ef.to_excel(writer, sheet_name='EXF_F1_failed_round3',index=False)

l1.to_excel(writer, sheet_name='LWL_F2_1',index=False)
l2.to_excel(writer, sheet_name='LWL_F2_2',index=False)
l3.to_excel(writer, sheet_name='LWL_F2_3',index=False)
lf.to_excel(writer, sheet_name='LWL_F2_failed_round3',index=False)

# Close the Pandas Excel writer and output the Excel file.
writer.save()

# For the people who calibrated

In [21]:
edf= pd.read_csv('C:/Users/tsb7592/Downloads/edf.csv', index_col=0)

In [22]:
ldf= pd.read_csv('C:/Users/tsb7592/Downloads/ldf.csv', index_col=0)

In [35]:
ecdf.gazeEngineState.unique()

array(['beforeCalibration', 'calibrating', 'afterCalibration', 'testing',
       'testCompleted'], dtype=object)

In [161]:
def make_table(df, ff):
    failed = list(ff.PIN.unique())
    failed.append('Porter')
    sdf = df[~df.PIN.isin(failed)]
    sdf['length'] =sdf.PIN.str.len()
    sdf=sdf[sdf.length ==6]
    
    testing = sdf[sdf.gazeEngineState =='testing']
    e1 = testing.groupby(['PIN','Assessment Name','itemID'])['gazeLocationName'].value_counts(normalize=True).unstack()
    e2 =testing.groupby(['PIN','Assessment Name','itemID'])['gazeLocationOnScreen'].value_counts(normalize=True).unstack()[True]
    rv = pd.merge(e1,e2, left_index=True, right_index=True)
    rv=rv.fillna(0).reset_index()
    
    rv.columns=['PIN', 'Assessment Name', 'itemID', 'away', 'left', 'right','onscreen']
    #Four critiria
    rv.loc[(rv['onscreen'] < 0.5),'classification'] = 'missingOff'
    #rv.loc[((rv['center'] >= 0.5)&(rv['onscreen'] >= 0.5)),'classification'] = 'center'
    rv.loc[((rv['left'] >= 0.5)&(rv['onscreen'] >= 0.5)),'classification'] = 'left'
    rv.loc[((rv['right'] >= 0.5)&(rv['onscreen'] >= 0.5)),'classification'] = 'right'
    rv.loc[((rv['right'] < 0.5)&(rv['left'] < 0.5)&(rv['onscreen'] >= 0.5)),'classification'] = 'missingAway'
    
    wide =rv.pivot_table(values=['onscreen','left', 'right','classification'], index=['PIN', 'Assessment Name'], columns='itemID', aggfunc='first')
    wide.columns = [col[1]+'_'+col[0] for col in wide.columns.values]
    wide=wide.reindex(sorted(wide.columns), axis=1)
    
    return wide

If proportion off screen >= 50%, “missingOff”;
if proportion left > 50%, “left”;
if proportion right > 50%, “right”;
if proportion on screen > 50% but both left and right proportions are < 50%, “missingAway”
For some items on EFX, it is “center/away” instead of left/right. For those items, if proportion onscreen > 50% and proportion center >50%, then “center”, else “missingOff” or “missingAway”.

In [157]:
wide_exf = make_table(edf,ef)
wide_exf

,,EXF_Blue1_classification,EXF_Blue1_left,EXF_Blue1_onscreen,EXF_Blue1_right,EXF_Blue2_classification,EXF_Blue2_left,EXF_Blue2_onscreen,EXF_Blue2_right,EXF_Blue3_classification,EXF_Blue3_left,...,VDR_7_onscreen,VDR_7_right,VDR_8_classification,VDR_8_left,VDR_8_onscreen,VDR_8_right,VDR_9_classification,VDR_9_left,VDR_9_onscreen,VDR_9_right
PIN,Assessment Name,,,,,,,,,,,,,,,,,,,,,
APL001,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.30,missingAway,0.45,1.00,0.21,left,0.89,1.00,0.07
APL002,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.29,0.00,missingOff,0.00,...,0.37,0.16,missingOff,0.25,0.33,0.08,missingAway,0.44,0.69,0.22
APL003,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,0.97,0.00,missingAway,0.00,...,0.96,0.22,left,0.56,1.00,0.22,missingAway,0.40,0.89,0.34
APL012,Assessment 1,missingAway,0.00,0.72,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.57,0.11,left,0.61,0.65,0.03,left,0.54,0.62,0.03
APL013,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.00,0.00,missingOff,0.00,...,0.50,0.01,missingOff,0.09,0.11,0.02,missingOff,0.04,0.04,0.00
APL014,Assessment 1,missingAway,0.00,0.83,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.98,0.21,missingAway,0.49,0.91,0.23,left,0.83,1.00,0.04
APL022,Assessment 1,NaN,NaN,NaN,NaN,missingAway,0.00,0.99,0.00,missingAway,0.00,...,0.01,0.00,left,0.52,0.66,0.06,left,0.90,0.96,0.01
APL031,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.00,0.00,NaN,NaN,...,0.55,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL042,Assessment 1,missingAway,0.00,0.85,0.00,missingAway,0.00,1.00,0.00,NaN,NaN,...,0.74,0.46,missingAway,0.40,0.71,0.21,missingAway,0.34,0.59,0.18
APL043,Assessment 1,missingOff,0.00,0.04,0.00,missingAway,0.00,0.84,0.00,missingOff,0.00,...,0.22,0.14,missingAway,0.32,0.62,0.19,missingAway,0.37,0.59,0.01
APL044,Assessment 1,missingAway,0.00,0.69,0.00,missingAway,0.00,1.00,0.00,missingOff,0.00,...,1.00,0.18,left,0.56,0.99,0.34,missingAway,0.30,0.88,0.40
APL051,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL052,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.97,0.63,right,0.13,1.00,0.64,missingAway,0.28,0.85,0.41
APL053,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.00,0.00,missingOff,0.00,...,0.67,0.67,missingOff,0.00,0.00,0.00,missingOff,0.00,0.03,0.03
APL061,Assessment 1,missingAway,0.00,0.92,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.90,0.09,missingOff,0.36,0.44,0.03,missingAway,0.26,0.51,0.08
APL062,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.36,left,0.61,1.00,0.35,left,0.94,1.00,0.05
APL063,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.00,0.00,missingOff,0.00,...,0.00,0.00,missingOff,0.00,0.00,0.00,missingOff,0.00,0.00,0.00
APL065,Assessment 2,missingAway,0.00,0.99,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.61,missingAway,0.19,0.99,0.46,missingAway,0.29,1.00,0.30
Cert 2,Assessment 1,missingOff,0.00,0.00,0.00,missingOff,0.00,0.12,0.00,missingOff,0.00,...,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL001,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,0.64,0.00,missingAway,0.00,...,0.95,0.26,left,0.67,1.00,0.22,left,0.67,0.94,0.14
DAL002,Assessment 1,missingAway,0.00,0.94,0.00,missingAway,0.00,0.99,0.00,missingAway,0.00,...,0.90,0.23,left,0.65,0.95,0.15,left,0.53,1.00,0.19
DAL012,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL024,Assessment 1,missingAway,0.00,0.95,0.00,missingAway,0.00,0.79,0.00,missingAway,0.00,...,0.29,0.00,missingOff,0.10,0.30,0.18,missingOff,0.28,0.32,0.01
DAL031,Assessment 1,missingAway,0.00,0.99,0.00,missingAway,0.00,0.99,0.00,missingAway,0.00,...,0.98,0.38,missingAway,0.25,0.65,0.37,missingAway,0.23,0.92,0.24
DAL041,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingOff,0.00,...,0.56,0.37,left,0.68,0.96,0.13,missingAway,0.37,0.82,0.27
DAL042,Assessment 1,missingAway,0.00,1.00,0.00,NaN,NaN,NaN,NaN,missingAway,0.00,...,0.97,0.02,left,0.63,0.91,0.24,left,0.55,0.73,0.08
DAL064,Assessment 1,missingOff,0.00,0.16,0.00,missingOff,0.00,0.32,0.00,missingOff,0.00,...,0.36,0.06,missingOff,0.23,0.44,0.11,missingOff,0.03,0.10,0.04
MNS011,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.72,0.33,right,0.12,0.83,0.59,missingAway,0.22,0.82,0.40
MNS021,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,0.96,0.00,missingAway,0.00,...,0.46,0.26,left,0.61,0.70,0.04,left,0.73,0.74,0.00
MNS031,Assessment 1,missingAway,0.00,0.78,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.07,left,0.72,1.00,0.08,left,0.74,0.97,0.10
MNS041,Assessment 2,missingAway,0.00,1.00,0.00,missingAway,0.00,0.96,0.00,missingAway,0.00,...,0.95,0.34,right,0.18,0.81,0.52,missingAway,0.07,0.77,0.49
MNS061,Assessment 1,missingAway,0.00,0.99,0.00,missingAway,0.00,0.92,0.00,missingAway,0.00,...,0.39,0.17,missingAway,0.27,0.75,0.44,missingAway,0.48,0.82,0.25
MNS062,Assessment 1,missingAway,0.00,0.98,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.78,0.10,missingAway,0.23,0.76,0.34,missingAway,0.27,0.75,0.48
MNS063,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.63,right,0.14,0.75,0.54,right,0.20,1.00,0.63
MNS064,Assessment 1,missingAway,0.00,0.97,0.00,missingOff,0.00,0.00,0.00,missingAway,0.00,...,0.18,0.18,missingAway,0.24,0.53,0.18,missingAway,0.21,0.51,0.16
MNS066,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,NaN,NaN,...,0.11,0.01,right,0.27,0.98,0.53,right,0.09,0.92,0.54
MNS067,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,1.00,0.02,left,0.68,0.99,0.16,left,0.87,1.00,0.03
STL001,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.96,0.02,left,0.71,0.93,0.08,left,0.60,0.85,0.21
STL011,Assessment 1,missingAway,0.00,0.95,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.82,0.30,missingAway,0.35,0.90,0.43,right,0.18,0.87,0.63
STL021,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.82,0.16,missingAway,0.36,0.79,0.22,missingAway,0.35,0.59,0.11
STL023,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.73,0.42,missingAway,0.25,0.91,0.37,missingAway,0.17,0.84,0.44
STL031,Assessment 5,missingAway,0.00,0.93,0.00,missingAway,0.00,0.75,0.00,missingOff,0.00,...,0.49,0.19,missingAway,0.32,0.74,0.25,missingAway,0.43,0.82,0.29
STL032,Assessment 1,missingAway,0.00,0.82,0.00,missingAway,0.00,0.86,0.00,missingAway,0.00,...,0.45,0.16,missingAway,0.41,0.58,0.09,missingOff,0.30,0.39,0.05
STL034,Assessment 1,missingAway,0.00,1.00,0.00,missingOff,0.00,0.00,0.00,missingOff,0.00,...,0.34,0.13,missingAway,0.15,0.60,0.39,missingOff,0.11,0.27,0.12
STL041,Assessment 1,missingAway,0.00,0.99,0.00,missingAway,0.00,0.99,0.00,missingAway,0.00,...,0.83,0.29,right,0.22,0.99,0.60,right,0.05,0.83,0.73
STL051,Assessment 1,missingAway,0.00,0.99,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.97,0.29,left,0.65,0.98,0.29,left,0.72,0.90,0.12
STL053,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,0.87,0.00,NaN,NaN,...,0.30,0.21,right,0.03,0.56,0.52,right,0.02,0.56,0.54
STL055,Assessment 1,missingAway,0.00,0.67,0.00,missingAway,0.00,0.64,0.00,NaN,NaN,...,0.53,0.37,missingAway,0.41,0.52,0.02,missingOff,0.05,0.24,0.14
STL056,Assessment 1,missingAway,0.00,1.00,0.00,missingAway,0.00,1.00,0.00,missingAway,0.00,...,0.95,0.25,left,0.83,0.98,0.04,left,0.73,0.99,0.13
STL064,Assessment 1,missingAway,0.00,0.59,0.00,missingOff,0.00,0.19,0.00,missingAway,0.00,...,0.83,0.35,missingAway,0.07,0.51,0.25,missingOff,0.29,0.41,0.05
STL066,Assessment 1,missingAway,0.00,0.51,0.00,missingAway,0.00,0.98,0.00,missingAway,0.00,...,0.68,0.01,left,0.57,0.73,0.08,missingOff,0.39,0.43,0.03

In [162]:
wide_lwl = make_table(ldf,lf)
wide_lwl

,,Ankle_Scissors_G7_classification,Ankle_Scissors_G7_left,Ankle_Scissors_G7_onscreen,Ankle_Scissors_G7_right,Apple_Truck_G2_classification,Apple_Truck_G2_left,Apple_Truck_G2_onscreen,Apple_Truck_G2_right,Bee_Cake_G6_classification,Bee_Cake_G6_left,...,Wolf_Jar_G3_onscreen,Wolf_Jar_G3_right,Woods_Tray_G7_classification,Woods_Tray_G7_left,Woods_Tray_G7_onscreen,Woods_Tray_G7_right,Zipper_Lion_G4_classification,Zipper_Lion_G4_left,Zipper_Lion_G4_onscreen,Zipper_Lion_G4_right
PIN,Assessment Name,,,,,,,,,,,,,,,,,,,,,
APL001,Assessment 1,NaN,NaN,NaN,NaN,right,0.15,0.89,0.67,NaN,NaN,...,1.00,0.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL002,Assessment 1,NaN,NaN,NaN,NaN,left,0.54,1.00,0.40,NaN,NaN,...,0.87,0.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL003,Assessment 1,NaN,NaN,NaN,NaN,right,0.12,0.98,0.85,NaN,NaN,...,1.00,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL004,Assessment 1,NaN,NaN,NaN,NaN,left,0.85,1.00,0.00,NaN,NaN,...,0.88,0.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL011,Assessment 1,NaN,NaN,NaN,NaN,right,0.15,0.90,0.73,NaN,NaN,...,0.92,0.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL012,Assessment 1,NaN,NaN,NaN,NaN,right,0.29,1.00,0.60,NaN,NaN,...,1.00,0.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL013,Assessment 1,NaN,NaN,NaN,NaN,right,0.16,0.82,0.58,NaN,NaN,...,0.04,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL014,Assessment 1,NaN,NaN,NaN,NaN,missingAway,0.36,0.92,0.45,NaN,NaN,...,0.45,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL022,Assessment 1,NaN,NaN,NaN,NaN,right,0.20,1.00,0.76,NaN,NaN,...,0.93,0.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL023,Assessment 1,NaN,NaN,NaN,NaN,right,0.23,0.93,0.69,NaN,NaN,...,1.00,0.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL033,Assessment 1,NaN,NaN,NaN,NaN,missingOff,0.14,0.41,0.26,NaN,NaN,...,0.83,0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL034,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL043,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.92,0.08,NaN,NaN,NaN,NaN,left,0.53,0.73,0.18
APL044,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.97,0.04,NaN,NaN,NaN,NaN,right,0.00,0.93,0.93
APL045,Assessment 1,NaN,NaN,NaN,NaN,right,0.00,0.57,0.57,NaN,NaN,...,0.99,0.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL046,Assessment 1,NaN,NaN,NaN,NaN,missingOff,0.21,0.31,0.11,NaN,NaN,...,0.02,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
APL052,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.86,0.17,NaN,NaN,NaN,NaN,left,0.65,0.88,0.10
APL061,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.00,NaN,NaN,NaN,NaN,missingOff,0.00,0.23,0.23
APL062,Assessment 1,left,0.59,0.80,0.09,NaN,NaN,NaN,NaN,left,0.73,...,NaN,NaN,left,0.63,0.63,0.00,NaN,NaN,NaN,NaN
APL063,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.58,0.10,NaN,NaN,NaN,NaN,right,0.00,0.64,0.63
APL066,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL002,Assessment 1,NaN,NaN,NaN,NaN,right,0.21,0.98,0.77,NaN,NaN,...,0.72,0.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL011,Assessment 1,NaN,NaN,NaN,NaN,right,0.00,0.51,0.51,NaN,NaN,...,0.01,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL021,Assessment 1,NaN,NaN,NaN,NaN,right,0.23,0.89,0.62,NaN,NaN,...,0.78,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL022,Assessment 1,NaN,NaN,NaN,NaN,right,0.09,0.95,0.84,NaN,NaN,...,0.55,0.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL032,Assessment 1,NaN,NaN,NaN,NaN,missingOff,0.04,0.05,0.01,NaN,NaN,...,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL041,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.30,NaN,NaN,NaN,NaN,right,0.23,0.98,0.70
DAL042,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.19,NaN,NaN,NaN,NaN,left,0.56,0.96,0.40
DAL064,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.93,0.15,NaN,NaN,NaN,NaN,right,0.05,0.87,0.78
MNS011,Assessment 1,NaN,NaN,NaN,NaN,right,0.23,0.93,0.58,NaN,NaN,...,0.70,0.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MNS021,Assessment 1,NaN,NaN,NaN,NaN,left,0.85,1.00,0.10,NaN,NaN,...,1.00,0.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MNS022,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MNS031,Assessment 1,NaN,NaN,NaN,NaN,right,0.00,1.00,0.96,NaN,NaN,...,0.98,0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MNS041,Assessment 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.07,NaN,NaN,NaN,NaN,left,0.50,0.95,0.38
MNS061,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.55,0.04,NaN,NaN,NaN,NaN,right,0.13,1.00,0.82
MNS063,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.17,NaN,NaN,NaN,NaN,right,0.14,0.98,0.83
MNS067,Assessment 1,right,0.44,1.00,0.56,NaN,NaN,NaN,NaN,left,0.55,...,NaN,NaN,left,0.66,0.99,0.33,NaN,NaN,NaN,NaN
STL001,Assessment 1,NaN,NaN,NaN,NaN,right,0.34,0.94,0.55,NaN,NaN,...,0.89,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL011,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.45,0.35,NaN,NaN,NaN,NaN,right,0.00,0.83,0.83
STL012,Assessment 1,NaN,NaN,NaN,NaN,left,0.57,0.74,0.14,NaN,NaN,...,0.76,0.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL022,Assessment 2,NaN,NaN,NaN,NaN,left,0.64,1.00,0.33,NaN,NaN,...,0.81,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL031,Assessment 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL032,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.24,NaN,NaN,NaN,NaN,missingOff,0.28,0.37,0.08
STL034,Assessment 1,NaN,NaN,NaN,NaN,right,0.07,0.71,0.63,NaN,NaN,...,0.96,0.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL041,Assessment 1,NaN,NaN,NaN,NaN,right,0.20,0.98,0.71,NaN,NaN,...,1.00,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STL051,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.96,0.27,NaN,NaN,NaN,NaN,left,0.54,1.00,0.46
STL053,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.91,0.05,NaN,NaN,NaN,NaN,missingOff,0.17,0.20,0.02
STL056,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.96,0.18,NaN,NaN,NaN,NaN,right,0.09,1.00,0.91
STL062,Assessment 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.46,NaN,NaN,NaN,NaN,right,0.20,0.88,0.67
STL064,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.38,NaN,NaN,NaN,NaN,right,0.47,1.00,0.53
STL066,Assessment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00,0.08,NaN,NaN,NaN,NaN,right,0.46,1.00,0.54

In [171]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('C:\\Users\\tsb7592\\OneDrive - Northwestern University\\Gaze_Feasibility_2022\\testing_freq.xlsx', engine='xlsxwriter')

#b. Summarize (inc. medians) by measure, overall and by age group
wide_exf.round(3).to_excel(writer, sheet_name='EXF')

wide_lwl.round(3).to_excel(writer, sheet_name='LWL')


# Close the Pandas Excel writer and output the Excel file.
writer.save()

# how many times does "eventName" : "beganHeadPlacement" (regardless of gazeEngineState) per record (minimum 1)

In [24]:
def HeadPlacement(df):
    hp = df[df.eventName=='beganHeadPlacement']
    return hp.groupby(['PIN','Assessment Name'])['eventName'].count()

In [25]:
ehp =HeadPlacement(edf)

In [26]:
lhp =HeadPlacement(ldf)

In [27]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('C:\\Users\\tsb7592\\OneDrive - Northwestern University\\Gaze_Feasibility_2022\\beganHeadPlacement.xlsx', engine='xlsxwriter')

#b. Summarize (inc. medians) by measure, overall and by age group
ehp.to_excel(writer, sheet_name='EXF_F1')
lhp.to_excel(writer, sheet_name='LWL_F2')

# Close the Pandas Excel writer and output the Excel file.
writer.save()

# how many times does "eventName" : "faceLeftScene" occur (please report this separately for by gazeEngineState) per record

In [28]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('C:\\Users\\tsb7592\\OneDrive - Northwestern University\\Gaze_Feasibility_2022\\faceLeftScene.xlsx', engine='xlsxwriter')

In [29]:
def FaceLeft(df, prefix):

    fl = df[df.eventName=='faceLeftScene']
    for state in df['gazeEngineState'].unique():
        
        sub = fl[fl.gazeEngineState== state]
        if sub.shape[0]>0:
            rv =sub.groupby(['PIN','Assessment Name'])['eventName'].count()
            rv.to_excel(writer, sheet_name=prefix +state)

In [30]:
FaceLeft(ldf,'LWL_')

In [31]:
FaceLeft(edf,'EXF_')

In [32]:
# Close the Pandas Excel writer and output the Excel file.
writer.save()

In [172]:
del writer

In [42]:
er= pd.merge(wrong, rsub , on =['timestamp','PIN','Assessment Name'])
fix =er[['Name','PIN','Assessment Name','timestamp']].drop_duplicates()

In [43]:
fix

      Name      PIN Assessment Name            timestamp
0      NaN  Ellie 2    Assessment 1  2022-05-18 14.35.30
19513  NaN  Kinsley    Assessment 1  2022-05-20 11.37.25