https://www.lighttag.io/blog/krippendorffs-alpha/

In [26]:
import simpledorff
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

df1 = pd.read_excel('C:/Users/tsb7592/Downloads/NBT Trainee Code Comparison_cleaned.xlsx', sheet_name='Toy Out of Reach1') 
df2 = pd.read_excel('C:/Users/tsb7592/Downloads/NBT Trainee Code Comparison_cleaned.xlsx', sheet_name='Toy Out of Reach2')
df3 = pd.read_excel('C:/Users/tsb7592/Downloads/NBT Trainee Code Comparison_cleaned.xlsx', sheet_name='Toy Out of Reach3')
#Load Your Dataframe
df3.head()

,Participant ID (video file name),Baseline Behavior,Intensity,Escalation,Coping,Rater,Notes,Unnamed: 7
0,P1_29mths,alert/calm,Moderate,Low,Low,Natasha,NaN,NaN
1,P3_27mths,alert/active,Low,Low,Moderate,Natasha,NaN,NaN
2,P10_27mths,alert/calm,Moderate,Low,Moderate,Natasha,NaN,NaN
3,P12_18mths,alert/calm,Moderate,Low,Low,Natasha,I considered the reaching across the table as ...,NaN
4,P18_23mths,alert/calm,Moderate,Low,Low,Natasha,NaN,NaN

In [24]:
df2.head()

,Participant ID (video file name),Baseline Behavior,Intensity,Escalation,Coping,Rater,Unnamed: 6,Unnamed: 7,Unnamed: 8,Intensity.1,Escalation.1,Coping.1,Notes,Unnamed: 13
0,P1_29mths,alert/calm,Low,None,High,Natasha,NaN,NaN,NaN,Moderate,Low,Low,NaN,NaN
1,P3_27mths,alert/active,Low,Low,Moderate,Natasha,NaN,NaN,NaN,Low,Low,Moderate,NaN,NaN
2,P10_27mths,alert/calm,Moderate,Low,Moderate,Natasha,NaN,NaN,NaN,Moderate,Low,Moderate,NaN,NaN
3,P12_18mths,alert/calm,Moderate,Low,Low,Natasha,NaN,NaN,NaN,Moderate,Low,Low,I considered the reaching across the table as ...,NaN
4,P18_23mths,alert/calm,Moderate,Low,Low,Natasha,NaN,NaN,NaN,Moderate,Low,Low,NaN,NaN

In [7]:
bb = pd.read_excel('C:/Users/tsb7592/Downloads/NBT Trainee Code Comparison_cleaned.xlsx', sheet_name='Bubbles') #Load Your Dataframe
bb.head()

C:\Users\tsb7592\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Participant ID (video file name),Baseline Behavior,Intensity,Predominance,Rater,Notes,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,P3_27mths,alert/calm,Low,Low,Natasha,Stop at 0:49 before giving bubble toy to child,NaN,NaN,NaN,NaN
1,P4_19mths,alert/active,Moderate,Moderate,Natasha,NaN,NaN,NaN,NaN,NaN
2,P10_27mths,alert/active,Moderate,Moderate,Natasha,NaN,NaN,NaN,NaN,NaN
3,P13_28mths,alert/active,Moderate,Moderate,Natasha,Stop at 0:43 before givving bubble toy to child,NaN,NaN,NaN,NaN
4,P18_23mths,alert/active,High,High,Natasha,NaN,NaN,NaN,NaN,NaN

In [28]:
import sys 

stdoutOrigin=sys.stdout 
sys.stdout = open("krippendorff's_alpha_output.txt", "w")

In [29]:
def ka(df, name='TOR'):
    a =simpledorff.calculate_krippendorffs_alpha_for_df(df, experiment_col='Participant ID (video file name)',
                                                 annotator_col='Rater',class_col='Baseline Behavior')
    b = simpledorff.calculate_krippendorffs_alpha_for_df(df, experiment_col='Participant ID (video file name)',
                                                 annotator_col='Rater',   class_col='Intensity')
    print("Baseline Behavior: ", round(a,2))
    print("Intensity: ", round(b,2))
    
    if name == 'TOR':
        c=simpledorff.calculate_krippendorffs_alpha_for_df(df, experiment_col='Participant ID (video file name)',
                                                 annotator_col='Rater',  class_col='Escalation')
        d = simpledorff.calculate_krippendorffs_alpha_for_df(df, experiment_col='Participant ID (video file name)',
                                                 annotator_col='Rater',   class_col='Coping')
        print("Escalation: ", round(c,2))
        print("Coping: ", round(d,2))
    else:
        c=simpledorff.calculate_krippendorffs_alpha_for_df(df, experiment_col='Participant ID (video file name)',
                                                 annotator_col='Rater',  class_col='Predominance ')
        print("Predominance: ", round(c,2))
    print('')    
    return

In [30]:
ka(df1)

In [31]:
ka(df2)

In [32]:
ka(df3)

In [33]:
ka(bb,'bubble')

In [34]:
sys.stdout.close()
sys.stdout=stdoutOrigin